"""memory tables (Phase 33)

Member 4's episodic and semantic memory in Postgres: archived investigations, one episode per
finding, and - for when the graph store is in memory - known entities and facts with their support.
Every row references its run with a cascade. See `.claude/architecture/memory.md`.

Revision ID: 7ae22a602a58
Revises: c5c5db1c59db
Create Date: 2026-10-04 23:58:31.183065

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ae22a602a58"
down_revision: str | Sequence[str] | None = "c5c5db1c59db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memory_entities",
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "entity_types",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "aliases",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "memory_facts",
        sa.Column("fact_id", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("subject_key", sa.String(length=255), nullable=False),
        sa.Column("predicate", sa.String(length=255), nullable=False),
        sa.Column("object", sa.Text(), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("fact_id"),
    )
    op.create_index(
        op.f("ix_memory_facts_object_key"), "memory_facts", ["object_key"], unique=False
    )
    op.create_index(
        "ix_memory_facts_subject_predicate",
        "memory_facts",
        ["subject_key", "predicate"],
        unique=False,
    )
    op.create_table(
        "memory_entity_runs",
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["key"], ["memory_entities.key"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("key", "run_id"),
    )
    op.create_table(
        "memory_episodes",
        sa.Column("episode_id", sa.String(length=80), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column(
            "sources",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("verification_status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("episode_id"),
    )
    op.create_index(
        op.f("ix_memory_episodes_created_at"), "memory_episodes", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_memory_episodes_run_id"), "memory_episodes", ["run_id"], unique=False)
    op.create_table(
        "memory_fact_support",
        sa.Column("fact_id", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["fact_id"], ["memory_facts.fact_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("fact_id", "run_id", "source"),
    )
    op.create_table(
        "memory_investigations",
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column(
            "snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("memory_investigations")
    op.drop_table("memory_fact_support")
    op.drop_index(op.f("ix_memory_episodes_run_id"), table_name="memory_episodes")
    op.drop_index(op.f("ix_memory_episodes_created_at"), table_name="memory_episodes")
    op.drop_table("memory_episodes")
    op.drop_table("memory_entity_runs")
    op.drop_index("ix_memory_facts_subject_predicate", table_name="memory_facts")
    op.drop_index(op.f("ix_memory_facts_object_key"), table_name="memory_facts")
    op.drop_table("memory_facts")
    op.drop_table("memory_entities")
    # ### end Alembic commands ###
