"""initial schema

Revision ID: c5c5db1c59db
Revises:
Create Date: 2026-09-24 11:02:35.800259

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5c5db1c59db"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector must exist before document_chunks. The compose init script also creates
    # it, but a database created any other way would otherwise fail here - and a
    # migration that only works on one provisioning path is not a migration.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current_phase", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column(
            "intent",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "final_result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("termination_reason", sa.String(length=32), nullable=True),
        sa.Column("replan_iterations", sa.Integer(), nullable=False),
        sa.Column("tool_calls_used", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_runs_status"), "agent_runs", ["status"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("line_count", sa.Integer(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column("omitted_note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_document_id"), "documents", ["document_id"], unique=False)
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("document_pk", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.String(length=255), nullable=False),
        sa.Column("locator", sa.String(length=255), nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("row", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
        sa.ForeignKeyConstraint(["document_pk"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_chunks_document_pk"), "document_chunks", ["document_pk"], unique=False
    )
    op.create_table(
        "execution_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("t_offset_ms", sa.Integer(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("task_id", sa.String(length=32), nullable=True),
        sa.Column("finding_id", sa.String(length=32), nullable=True),
        sa.Column("tool_name", sa.String(length=64), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_events_run_offset", "execution_events", ["run_id", "t_offset_ms"], unique=False
    )
    op.create_index(
        op.f("ix_execution_events_event_type"), "execution_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_execution_events_run_id"), "execution_events", ["run_id"], unique=False
    )
    op.create_table(
        "findings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("finding_id", sa.String(length=32), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("classification", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("resolution_rate", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("evidence_strength", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("source_agreement", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "finding_id", name="uq_finding_per_run"),
    )
    op.create_index(
        op.f("ix_findings_classification"), "findings", ["classification"], unique=False
    )
    op.create_index(op.f("ix_findings_run_id"), "findings", ["run_id"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("task_id", sa.String(length=32), nullable=False),
        sa.Column("task_type", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "inputs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "output",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("selected_tool", sa.String(length=64), nullable=False),
        sa.Column("selection_mode", sa.String(length=32), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("failure_class", sa.String(length=32), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("created_by_revision", sa.Integer(), nullable=False),
        sa.Column("created_for_gap_id", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "task_id", name="uq_task_per_run"),
    )
    op.create_index(op.f("ix_tasks_run_id"), "tasks", ["run_id"], unique=False)
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_table(
        "tool_executions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("task_id", sa.String(length=32), nullable=False),
        sa.Column("call_id", sa.String(length=32), nullable=False),
        sa.Column("tool_name", sa.String(length=64), nullable=False),
        sa.Column(
            "arguments",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "output",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("failure_class", sa.String(length=32), nullable=True),
        sa.Column(
            "sources",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("execution_time_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tool_executions_run_id"), "tool_executions", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_tool_executions_task_id"), "tool_executions", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_tool_executions_tool_name"), "tool_executions", ["tool_name"], unique=False
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("finding_pk", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.String(length=255), nullable=False),
        sa.Column("locator", sa.String(length=255), nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("row", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("resolution", sa.String(length=32), nullable=False),
        sa.Column("resolution_note", sa.Text(), nullable=False),
        sa.Column("strength", sa.String(length=32), nullable=False),
        sa.Column("relevance_score", sa.Float(), nullable=False),
        sa.Column("retrieved_by_task_id", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(["finding_pk"], ["findings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evidence_finding_pk"), "evidence", ["finding_pk"], unique=False)
    op.create_index(op.f("ix_evidence_resolution"), "evidence", ["resolution"], unique=False)
    op.create_table(
        "evidence_gaps",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("finding_pk", sa.Integer(), nullable=False),
        sa.Column("gap_id", sa.String(length=32), nullable=False),
        sa.Column("gap_type", sa.String(length=48), nullable=False),
        sa.Column("missing", sa.Text(), nullable=False),
        sa.Column("severity", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("suggested_query", sa.Text(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("resolved_by_task_id", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(["finding_pk"], ["findings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_gaps_finding_pk"), "evidence_gaps", ["finding_pk"], unique=False
    )
    op.create_index(op.f("ix_evidence_gaps_gap_type"), "evidence_gaps", ["gap_type"], unique=False)
    op.create_index(op.f("ix_evidence_gaps_resolved"), "evidence_gaps", ["resolved"], unique=False)
    op.create_table(
        "task_dependencies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_pk", sa.Integer(), nullable=False),
        sa.Column("depends_on_task_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["task_pk"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_task_dependencies_task_pk"), "task_dependencies", ["task_pk"], unique=False
    )
    op.create_table(
        "verifications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("finding_pk", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("verifier", sa.String(length=64), nullable=False),
        sa.Column("degraded", sa.Boolean(), nullable=False),
        sa.Column("degraded_reason", sa.Text(), nullable=False),
        sa.Column(
            "issues",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["finding_pk"], ["findings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verifications_finding_pk"), "verifications", ["finding_pk"], unique=False
    )
    op.create_index(op.f("ix_verifications_status"), "verifications", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_verifications_status"), table_name="verifications")
    op.drop_index(op.f("ix_verifications_finding_pk"), table_name="verifications")
    op.drop_table("verifications")
    op.drop_index(op.f("ix_task_dependencies_task_pk"), table_name="task_dependencies")
    op.drop_table("task_dependencies")
    op.drop_index(op.f("ix_evidence_gaps_resolved"), table_name="evidence_gaps")
    op.drop_index(op.f("ix_evidence_gaps_gap_type"), table_name="evidence_gaps")
    op.drop_index(op.f("ix_evidence_gaps_finding_pk"), table_name="evidence_gaps")
    op.drop_table("evidence_gaps")
    op.drop_index(op.f("ix_evidence_resolution"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_finding_pk"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_tool_executions_tool_name"), table_name="tool_executions")
    op.drop_index(op.f("ix_tool_executions_task_id"), table_name="tool_executions")
    op.drop_index(op.f("ix_tool_executions_run_id"), table_name="tool_executions")
    op.drop_table("tool_executions")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_run_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_findings_run_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_classification"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_execution_events_run_id"), table_name="execution_events")
    op.drop_index(op.f("ix_execution_events_event_type"), table_name="execution_events")
    op.drop_index("ix_events_run_offset", table_name="execution_events")
    op.drop_table("execution_events")
    op.drop_index(op.f("ix_document_chunks_document_pk"), table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index(op.f("ix_documents_document_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_agent_runs_status"), table_name="agent_runs")
    op.drop_table("agent_runs")
    # ### end Alembic commands ###
