"""workspaces and document provenance (Phase 40)

Member 2's workspace-scoped retrieval: a document belongs to a workspace, once, with its SHA-256
and parser. Server defaults let the columns be added to a table that already has rows.

Revision ID: c6e375938463
Revises: 7ae22a602a58
Create Date: 2026-10-05 23:34:42.064284

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6e375938463"
down_revision: str | Sequence[str] | None = "7ae22a602a58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column("workspace_id", sa.String(length=64), nullable=False, server_default="default"),
    )
    op.add_column(
        "documents", sa.Column("sha256", sa.String(length=64), nullable=False, server_default="")
    )
    op.add_column(
        "documents", sa.Column("parser", sa.String(length=32), nullable=False, server_default="")
    )
    op.create_index(op.f("ix_documents_workspace_id"), "documents", ["workspace_id"], unique=False)
    op.create_unique_constraint(
        "uq_documents_workspace_document", "documents", ["workspace_id", "document_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_documents_workspace_document", "documents", type_="unique")
    op.drop_index(op.f("ix_documents_workspace_id"), table_name="documents")
    op.drop_column("documents", "parser")
    op.drop_column("documents", "sha256")
    op.drop_column("documents", "workspace_id")
    # ### end Alembic commands ###
