"""The typed spine.

Every object crossing a component boundary is defined here (invariant #2). This package
depends on nothing else in the application — importing it must never pull in an engine, a
database session or a provider. That one-way dependency is what lets the schemas be the
contract rather than a consequence of the implementation.

Dependency order within the package:

    common -> objective, intent, tool, evidence
           -> verification -> finding
           -> task -> plan
           -> event, execution -> result
"""

from app.schemas.common import (
    CostHint,
    EventId,
    EvidenceId,
    FailureClass,
    FindingId,
    FrozenModel,
    GapId,
    JarvisModel,
    JsonDict,
    Money,
    NonEmptyStr,
    RunId,
    Severity,
    SourceLocator,
    TaskId,
    ToolCallId,
    UnitFloat,
    evidence_id,
    finding_id,
    gap_id,
    is_retryable,
    new_event_id,
    new_run_id,
    new_tool_call_id,
    task_id,
    utcnow,
)
from app.schemas.event import (
    PHASE_EVENTS,
    REDACTED_PAYLOAD_KEYS,
    EventFilter,
    EventType,
    ExecutionEvent,
    ExecutionTrace,
)
from app.schemas.evidence import (
    ClaimElement,
    Evidence,
    EvidenceGap,
    EvidenceRef,
    EvidenceStrength,
    GapType,
    ResolutionStatus,
)
from app.schemas.execution import (
    Budget,
    ExecutionState,
    Observation,
    RunPhase,
    RunStatus,
    TerminationReason,
)
from app.schemas.finding import (
    Confidence,
    Finding,
    FindingClassification,
)
from app.schemas.intent import (
    Constraints,
    Intent,
    Operation,
    OutputFormat,
    RequiredOperation,
    UnsupportedOperation,
)
from app.schemas.objective import (
    AttachedDocument,
    DocumentKind,
    Objective,
    ObjectiveScope,
    SuccessCriterion,
)
from app.schemas.plan import (
    Plan,
    PlanRepair,
    PlanRevision,
    PlanValidationResult,
    PlanViolation,
    RepairAction,
    RevisionTrigger,
    ViolationCode,
)
from app.schemas.result import (
    REQUIRED_SECTIONS,
    AgentResult,
    ExecutionSummary,
    FinalReport,
    Limitation,
    ReportSection,
    SectionKind,
)
from app.schemas.task import (
    LEGAL_TRANSITIONS,
    TASK_CAPABILITY,
    TASK_SATISFIES,
    TERMINAL_STATUSES,
    IllegalTransitionError,
    Task,
    TaskDependency,
    TaskResult,
    TaskStatus,
    TaskType,
    can_transition,
)
from app.schemas.tool import (
    SelectionMode,
    ToolCall,
    ToolCapability,
    ToolDefinition,
    ToolError,
    ToolResult,
    ToolSelection,
)
from app.schemas.verification import (
    IssueType,
    VerificationIssue,
    VerificationRequest,
    VerificationResult,
    VerificationStatus,
)

__all__ = [
    "LEGAL_TRANSITIONS",
    "PHASE_EVENTS",
    "REDACTED_PAYLOAD_KEYS",
    "REQUIRED_SECTIONS",
    "TASK_CAPABILITY",
    "TASK_SATISFIES",
    "TERMINAL_STATUSES",
    "AgentResult",
    "AttachedDocument",
    "Budget",
    "ClaimElement",
    "Confidence",
    "Constraints",
    "CostHint",
    "DocumentKind",
    "EventFilter",
    "EventId",
    "EventType",
    "Evidence",
    "EvidenceGap",
    "EvidenceId",
    "EvidenceRef",
    "EvidenceStrength",
    "ExecutionEvent",
    "ExecutionState",
    "ExecutionSummary",
    "ExecutionTrace",
    "FailureClass",
    "FinalReport",
    "Finding",
    "FindingClassification",
    "FindingId",
    "FrozenModel",
    "GapId",
    "GapType",
    "IllegalTransitionError",
    "Intent",
    "IssueType",
    "JarvisModel",
    "JsonDict",
    "Limitation",
    "Money",
    "NonEmptyStr",
    "Objective",
    "ObjectiveScope",
    "Observation",
    "Operation",
    "OutputFormat",
    "Plan",
    "PlanRepair",
    "PlanRevision",
    "PlanValidationResult",
    "PlanViolation",
    "RepairAction",
    "ReportSection",
    "RequiredOperation",
    "ResolutionStatus",
    "RevisionTrigger",
    "RunId",
    "RunPhase",
    "RunStatus",
    "SectionKind",
    "SelectionMode",
    "Severity",
    "SourceLocator",
    "SuccessCriterion",
    "Task",
    "TaskDependency",
    "TaskId",
    "TaskResult",
    "TaskStatus",
    "TaskType",
    "TerminationReason",
    "ToolCall",
    "ToolCallId",
    "ToolCapability",
    "ToolDefinition",
    "ToolError",
    "ToolResult",
    "ToolSelection",
    "UnitFloat",
    "UnsupportedOperation",
    "VerificationIssue",
    "VerificationRequest",
    "VerificationResult",
    "VerificationStatus",
    "ViolationCode",
    "can_transition",
    "evidence_id",
    "finding_id",
    "gap_id",
    "is_retryable",
    "new_event_id",
    "new_run_id",
    "new_tool_call_id",
    "task_id",
    "utcnow",
]
